### ISSUE TITLE
'_ssl._SSLSocket' object has no attribute 'issuer'

### ISSUE THREAD

**Issue by schulmar** [vint21h/nagios-notification-jabber#2]
When trying to use the script I am confronted with this error:

> ERROR: Couldn't connect or auth on server. '_ssl._SSLSocket' object has no attribute 'issuer'

After following this [thread](https://labs.riseup.net/code/issues/9074), I added `secure=1` to the parameters of `client.connect()` which resulted in the error message:

> ERROR: Couldn't connect or auth on server. Client instance has no attribute 'Dispatcher'

I am using xmpppy-0.5.0rc1 on Python2.7.

**Comment by vint21h** [comment]
As i know development of original http://xmpppy.sourceforge.net/ library
stopped. So if you want, you can use one of forks, for example -
https://github.com/ArchipelProject/xmpppy. This fork work on Python27 and
new SSL API.

**Comment by schulmar** [comment]
That worked. 

It is a bit unfortunate that `pip`, `easy_install` and setuptools will automatically pull the outdated version. Although that is more a problem of the repositories than of your program, I would say it should be noted in the in the installation instructions.

**Comment by vint21h** [comment]
New version with updated readme released.
